import type { Metadata } from 'next';
import Image from 'next/image';
import { ArrowLink, Eyebrow } from '@/components/ui';
import { Closing } from '@/components/closing';
import { Reveal } from '@/components/reveal';
import { contact } from '@/lib/content';
export const metadata: Metadata = { title: 'Our World', description: 'Meet Luxury Performance, the automotive performance division of The Luxury Group in Dubai. Genuine parts, informed advice and a personal approach.' };
export default function About() {
  return <><section className="page-intro"><Eyebrow>Our world / Luxury Performance</Eyebrow><h1>A shared passion.<br /><span>An individual drive.</span></h1><div className="page-intro-bottom"><span className="tiny-label">Dubai, United Arab Emirates<br />A division of The Luxury Group</span><p>For the enthusiast. The detail obsessive. The person who knows that the right car is only the beginning.</p></div></section><div className="interior-hero"><Image src="/images/headquarters.webp" fill priority sizes="100vw" alt="The Luxury Group headquarters in Al Quoz, Dubai" /><span className="image-bottom-label">One home. A world of automotive possibility.</span></div>
  <section className="about-manifesto section-pad"><div><Eyebrow number="01">Who we are</Eyebrow><Image src="/brand/emblem.png" width={185} height={67} alt="Luxury Performance wing emblem" className="about-emblem" /></div><Reveal><h2>Built around cars.<br /><span className="text-muted">Driven by people.</span></h2><p>Luxury Performance is the performance division of The Luxury Group. Based in Dubai, we connect enthusiasts, collectors and specialist workshops with genuine automotive components and world-renowned aftermarket brands.</p><p>Our world goes beyond one upgrade. Performance exhausts, carbon aerodynamics, forged wheels, suspension and genuine OEM components all have a place. The starting point is always the same: your car, your priorities and the way you want it to feel.</p><p>With the wider group’s automotive experience behind us, we combine access to exceptional products with personal guidance, fitment support and connections to installation specialists.</p><ArrowLink href="/contact">Talk to our team</ArrowLink></Reveal></section>
  <section className="approach-section section-pad"><Reveal><Eyebrow number="02">The way we work</Eyebrow><h2>Considered from<br /><span className="text-muted">the first conversation.</span></h2><div className="approach-grid">{[{title:'Understand the ambition.',text:'A daily drive, a weekend car or a personal collection. We begin with how you use your car and what you want to change.'},{title:'Make the right choices.',text:'We guide you through brands, components and vehicle fitment, helping you build a specification that works as a whole.'},{title:'Stay with the details.',text:'From availability and ordering to installation guidance, we help you understand each next step and connect you with specialist support.'}].map((item,index)=><div className="approach-card" key={item.title}><span>0{index+1} /</span><h3>{item.title}</h3><p>{item.text}</p></div>)}</div></Reveal></section>
  <section className="about-location section-pad" id="dubai"><div className="about-location-image"><Image src="/images/sf90.webp" alt="Ferrari SF90 at a specialist Dubai workshop" fill sizes="(max-width: 700px) 90vw, 45vw" /></div><Reveal><Eyebrow number="03">At home in Dubai</Eyebrow><h2>Local knowledge.<br /><span className="text-muted">A wider perspective.</span></h2><p>Our home in Al Quoz puts us at the heart of Dubai’s automotive community. As part of The Luxury Group, we share a world of supercars, specialist care and people who understand what makes them special.</p><div className="location-details">4th Street, Al Quoz Industrial 3<br />Dubai, United Arab Emirates<br /><span className="text-muted">Monday–Saturday · 10am–8pm</span></div><ArrowLink href={contact.maps} external>Find us in Dubai</ArrowLink></Reveal></section><Closing title={'Same passion.\nNew possibilities.'} /></>;
}
