import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { Eyebrow, ArrowLink } from '@/components/ui';
import { Expertise } from '@/components/expertise';
import { Reveal } from '@/components/reveal';
import { ProgrammeCard } from '@/components/programme-card';
import { Closing } from '@/components/closing';
import { programmes } from '@/lib/content';

export default function Home() {
  return <>
    <section className="hero" aria-labelledby="hero-title">
      <div className="hero-heading"><div className="hero-kicker"><span className="live-dot" />Dubai born. Performance driven.</div><h1 id="hero-title">Beyond <span>ordinary.</span><span className="hero-asterisk" aria-hidden="true">✳</span></h1><div className="hero-intro"><p>For those who see a car.<br />And imagine something more.</p><a href="#expertise" className="hero-scroll" aria-label="Discover our expertise"><ArrowDown size={19} strokeWidth={1.3} /></a></div></div>
      <div className="hero-visual"><Image src="/images/hero-luxury-group.webp" alt="Supercar lineup outside The Luxury Group headquarters in Al Quoz, Dubai" fill priority sizes="(max-width: 700px) calc(100vw - 18px), calc(100vw - 32px)" quality={95} /><div className="hero-image-shade" /><div className="hero-image-top"><span>THE ART OF AUTOMOTIVE EXPRESSION</span><span>EST. DUBAI / UAE</span></div><div className="hero-image-bottom"><span className="hero-image-caption"><span className="tiny-label">Our home / Dubai</span>A shared passion. An extraordinary place.</span><Link href="/about#dubai" className="hero-programme-link">Discover our world <span><ArrowUpRight size={21} /></span></Link></div></div>
      <div className="hero-foot"><span>Performance. Design. Individuality.</span><span>Luxury Performance — A division of The Luxury Group</span></div>
    </section>
    <section className="intro section-pad"><Reveal><Eyebrow number="01">A different kind of drive</Eyebrow><div className="intro-grid"><div className="intro-side"><span className="large-plus">+</span><p>Not just what you drive.<br />How it makes you feel.</p></div><div><h2>Exceptional comes<br />as standard.<br /><span className="text-muted">Individual is up to you.</span></h2><div className="intro-copy"><p>We bring the world’s most exciting automotive brands to people who care about every detail. Performance, carbon, wheels and more — thoughtfully selected, expertly supported, unmistakably yours.</p><ArrowLink href="/about">Meet Luxury Performance</ArrowLink></div></div></div></Reveal></section>
    <section className="expertise-section section-pad" id="expertise"><Reveal><div className="section-heading"><Eyebrow number="02">Our expertise</Eyebrow><h2>Every detail.<br /><span className="text-muted">A difference.</span></h2></div><Expertise /></Reveal></section>
    <section className="programmes-section section-pad"><Reveal><div className="section-heading horizontal"><div><Eyebrow number="03">Selected programmes</Eyebrow><h2>Extraordinary,<br /><span className="text-muted">from every angle.</span></h2></div><ArrowLink href="/programmes">Explore all programmes</ArrowLink></div><div className="programme-grid home-programmes">{programmes.slice(0, 2).map((programme, index) => <ProgrammeCard key={programme.slug} programme={programme} index={index} />)}</div></Reveal></section>
    <section className="partners-strip section-pad"><span className="tiny-label">Exceptional names. A shared obsession.</span><div className="partners-logos" aria-label="Brands: NOVITEC, TECHART, FI Exhaust and Valvetronic"><span className="partner-novitec">NOVITEC</span><span className="partner-techart">TECHART</span><span className="partner-fi">Fi<span>EXHAUST</span></span><span className="partner-valvetronic">VALVETRONIC<small>DESIGNS</small></span></div></section>
    <section className="world-section"><div className="world-image"><Image src="/images/workshop.webp" fill sizes="(max-width: 800px) 100vw, 55vw" alt="Porsche in a specialist performance workshop" /></div><div className="world-copy"><Reveal><Eyebrow dark number="04">The Luxury Performance approach</Eyebrow><h2>Good parts.<br />Great judgement.</h2><p>The difference is knowing what works together. We connect you with genuine components, informed advice and installation support — from the first idea to the finer details.</p><div className="world-principles"><span>01 / Listen first</span><span>02 / Specify with purpose</span><span>03 / Support every detail</span></div><ArrowLink href="/about" light>Discover our world</ArrowLink></Reveal></div></section>
    <section className="location-section section-pad"><Reveal><div className="location-heading"><Eyebrow>Rooted in Dubai. Connected worldwide.</Eyebrow><p>Part of The Luxury Group.<br />One shared passion for exceptional automobiles.</p></div><Link href="/about#dubai" className="location-banner"><Image src="/images/headquarters.webp" fill sizes="90vw" alt="The Luxury Group headquarters with a lineup of supercars in Dubai" /><div className="location-overlay" /><div className="location-caption"><span>Our home.<br /><strong>Your next chapter.</strong></span><span className="location-arrow"><ArrowUpRight size={35} strokeWidth={1} /></span></div><span className="location-address">AL QUOZ, DUBAI / THE LUXURY GROUP</span></Link></Reveal></section>
    <Closing />
  </>;
}
